core: 7.x
api: 2

defaults:
  projects:
    subdir: contrib

includes:
  - ../../stock/dkan/lock.yml
  - contrib.make.yml
  - custom.make.yml

projects:

  # Hook into install profile to add DemTools DKAN customizations.
  dkan:
    download:
      branch: 7.x-1.x
      revision: 7.x-1.14.1
    patch:
      # Add dependency on our keystone feature and extra install task.
      - "https://github.com/NuCivic/dkan/compare/7.x-1.13.2...nditech:nditech-dkan-7.x-1.13.2.patch"
      # Add a custom date format (mmm-yyyy). Patch need a re-roll.
#      - "https://github.com/nditech/dkan/commit/1933d763817bf4b6b0ed93626ddbd0ed6bfd218f.patch"

  # Overrides for security releases.
  entityreference: { version: ~ }
  entity: { version: ~ }
  file_resup: { version: ~ }
  features: { version: ~ }
  views: { version: ~ }
