core: 7.x
api: 2

defaults:
  projects:
    subdir: contrib

translations:
  - ar
  - fr
  - id
  - ru
  - es

includes:
  - ../../stock/petitions/lock.yml
  - contrib.make.yml
  - custom.make.yml

projects:
  petitions:
    type: profile
    subdir: '.'
    download:
      type: git
      url: 'https://github.com/nditech/demtools-petitions'
      branch: 'demtools'
      # Allow the new branch's revision to override the one in the stock lock
      # file.
      revision: ~
